# Используем официальный образ Python
FROM python:3.10-slim

# Устанавливаем зависимости для работы с MySQL и FastAPI
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем файлы requirements.txt и устанавливаем зависимости
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Копируем все файлы приложения в контейнер
COPY . .

# Указываем порт, который будет использоваться для приложения
EXPOSE 8000

# Команда для запуска FastAPI-приложения с Uvicorn
CMD ["python", "main.py"]