# Укажите базовый образ с Node.js
FROM node:16 AS build

# Установите рабочую директорию
WORKDIR /app

# Копируйте package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Установите зависимости
RUN npm install

RUN npm install axios

# Копируйте все файлы в рабочую директорию
COPY . .
